### PR TITLE
Revamp entire website

### LINKED ISSUE #17: Thoughts on a revamp?
Following https://github.com/sphinx-themes/sphinx-themes.org/issues/3#issuecomment-660598014, I spent a few cycles iterating on this and came up with https://github.com/pradyunsg/sphinx-themes. I added a few themes to demonstrate the approach and a very basic/minimal index page for this, which [is online now](https://pradyunsg.me/sphinx-themes/).

I started from-scratch and came away with quite a different approach for doing things. This resulted in:

- Generating demos, and screenshots (w/ selenium) in a GitHub Action job.
- Keep all theme-related information in a JSON file.
- No requirement on docker -- plain Python scripts w/ [nox](https://nox.readthedocs.io/).
- No generated HTML/CSS/images are checked into the master branch.
- Preview images contain multiple viewport sizes! :tada:

Notably, the main changes due to all of this are:

- Significantly lower barrier for adding new themes! :tada:
- Themes have to be installable from PyPI, usable against the current Sphinx version
  - This is a reasonable assumption, and helps ensure that people can actually use the themes. :)
- No conf.py is included/provided
  - The theme should have documentation about this, so the gallery doesn't need to cover this.
  - It should be easy-enough to add this if we really want to (I don't)
- 2 column vs 3 column layout
  - I wanted this to include additional viewport sizes, so, yea, I think this design change is worthwhile. :)

---

This was mostly an over-the-boring-day thing, and there's definitely scope for improvement in the automation (eg: separating render-with-themes vs generate-screenshots). If there's interest in bringing in most (all?) of that codebase into this one, I'd like to hear about it! ^>^

### PR DESCRIPTION
**Pull request by pradyunsg**
Closes #17

This brings in the changes from https://github.com/pradyunsg/sphinx-themes/ into this project, replacing the entire existing project tree with that repository. Notable changes to that repository since last discussion:

- Significantly cleaned up generation + CI pipelines
- A completely rewritten README + CONTRIBUTING guide
  - I spent wayy too much time on this, but this covers basically everything so that's good. :)
- `conf.py` files are included and linked-to from the gallery
- CI builds now includes the "generated-site" as an artifact that can be downloaded
- Relicensed to BSD-2-Clause (like the current repository)

Post-merge tasks for maintainers/admins:

- Change "branch for GitHub Pages", from "master" to "gh-pages".

Notably, this PR *technically* has fewer themes than `master`, but I say we add them in a follow up because... well, I'd like to do the "add-the-themes" task later and leave a bit of space for others to pick up some of the themes as well. :)

### CODE REVIEW

**Comment by schettino72** [comment]
:+1:  IMHO A single-column layout (for large screens) would work better.

**Comment by pradyunsg** [comment]
I tried that locally yesterday, but it didn't look right to me on tablets, a 15" laptop screen or on my big fat 34" monitor.

Having a single column means that all the width goes towards to making the images bigger, something that I didn't feel was worthwhile given that it's possible to get a good idea for how a theme looks even at half width and if you really need a closer look, there's a preview link available. :)

**Comment by schettino72** [comment]
Well, dont need to use 100% of the screen width.
i.e. It is just easier to compare the look on mobile when all images are aligned vertically.

Anyway, just my 2 cents. Thanks for great work.

**Comment by pradyunsg** [comment]
@shirou Nudge.

**Comment by shirou** [comment]
ah, sorry for late response. OK. let's merge this. but I want to replace the current website after adding themes as much as possible. 

Thank you for your great contribution!!

**Comment by pradyunsg** [comment]
Whee! Thanks @shirou! ^>^

I'll add the additional sites in a few follow up PRs! Thanks for the push access here. :)

**Pull request merged**
