### PR TITLE
Port msmb_theme to v2

### PR DESCRIPTION
**Pull request by mgeier**
To advance #25.

Previous `conf.py`:

```
html_theme = 'msmb_theme'
import msmb_theme
html_theme_path = [msmb_theme.get_html_theme_path()]
```

### CODE REVIEW

**Comment by pradyunsg** [comment]
This has an un-declared dependency on Sphinx-RTD -- so I'm inclined to exclude it unless this is fixed upstream.

**Comment by mgeier** [comment]
I'm not sure what's going wrong there, but the dependency seems to be declared:

https://github.com/msmbuilder/msmb_theme/blob/ef9a94f97343d7cc2ef5bd1f0bd64fe2a8bf1b19/setup.py#L43

**Comment by pradyunsg** [comment]
That change never got release IIUC.

**Comment by mgeier** [comment]
Oh, I see!

**Pull request closed without merging**
