### PR TITLE
Add insipid theme

### PR DESCRIPTION
**Pull request by mgeier**
I would like to add my own *insipid* theme.

I haven't tried it locally, I hope I didn't break CI.

### CODE REVIEW

**Comment by pradyunsg** [comment]
Hmmmm... I should update the pre-commit action. One moment while I do that on the master branch. :)

**Comment by mgeier** [comment]
Thanks @pradyunsg, I've re-based but the error still appears ...?

**Comment by pradyunsg** [comment]
Yup yup - I think I found the issue now, which should be fixed in the latest commit. :)

**Comment by pradyunsg** [comment]
No need to rebase btw. I can merge this as is!

**Comment by mgeier** [comment]
Cool, thanks a lot @pradyunsg!
BTW, I really like the new site design!

**Pull request merged**
