### PR TITLE
Address initial feedback from April 2021 revamp

### PR DESCRIPTION
**Pull request by pradyunsg**
/cc @choldgraf @jorisvandenbossche for pydata-sphinx-theme re-addition -- feedback welcome on how to handle the way that pydata-sphinx-theme handles navigation!

### CODE REVIEW

**Comment by pradyunsg** [comment]
> feedback welcome on how to handle the way that pydata-sphinx-theme handles navigation!

I'm deploying this right now, but feel free to reply on this PR about this (or to file a new issue to discuss this).

I don't think pydata-sphinx-theme is being fairly represented here, so, I'd like to hear feedback on how to handle it.

**Comment by jorisvandenbossche** [comment]
Nice revamp!

Yeah, generally the pydata-sphinx-theme is targeting sites that have a few top-level items. While the current demo docs is rather written for a sidebar. 
I don't know what the best solution would be for this, apart from having two versions of the demo docs .. Although it might be that just replacing the main index.rst could already be sufficient without having to duplicate all the rest.

**Comment by pradyunsg** [comment]
One option is to have an alternative `root_doc` I think. Setting it to something like `index-nested-nav.rst`, with that being a better structured for pydata-sphinx-theme?

I guess how the sphinx-basic-ng conversation goes around handling navigation will inform the choices to make here.

**Comment by choldgraf** [comment]
Something like that sounds reasonable to me, I think there is value in encouraging people to try the topbar-style layout in more themes, even if it is a bit different from traditional sphinx sites

**Comment by pradyunsg** [comment]
It might even make sense to just have that by default maybe? IDK yet.

I'll experiment and see if I can come up with something that just works for everything.

**Pull request merged**
