### PR TITLE
Updated instructions

### PR DESCRIPTION
**Pull request by romnnn**
I have had some troubles with the contribution instructions:
- I had to install `parcel`
- I had to manually run `npm install` in `js/`

With this PR I have solved the issues I had and did some formatting and re-phrasing to `README.rst`.

I am open for feedback. Great website!

### CODE REVIEW

**Comment by shirou** [comment]
Wow, great! Thank you so much for your contribution!!

Is this PR separated from #9, or if I merge this PR, can I close #9?

**Comment by romnnn** [comment]
Thanks!
These are separate PR's in case something needed to be improved :)

**Comment by romnnn** [comment]
Nevermind, I did not branch out of master. I closed #9.

**Comment by shirou** [comment]
I has been update the site, https://sphinx-themes.org/html/romnnn_sphinx_press_theme/press/index.html. Thank you !

**Pull request merged**
