### PR TITLE
Update ci.yaml to use newer pre-commit version, v3.0.0

### PR DESCRIPTION
**Pull request by shirou**

### CODE REVIEW

**Comment by shirou** [comment]
https://github.com/pre-commit/action/tree/main

> this action is in maintenance-only mode and will not be accepting new features.
> generally you want to use [pre-commit.ci](https://pre-commit.ci/) which is faster and has more features.

hmm. Should we stop using this action? or move to pre-commit.ci?

**Comment by pradyunsg** [comment]
@shirou I've filed #131 to fix the pre-commit failures. The failure is basically https://github.com/PyCQA/isort/pull/2078 :)

I think adopting pre-commit.ci isn't strictly necessary but if you think that's preferable, please feel welcome to add that! We should remove the pre-commit CI job then and change the required checks to require pre-commit.ci's check instead of the current pre-commit check from GitHub Actions.

**Comment by shirou** [comment]
fixed by #131

**Comment by shirou** [comment]
I think no need to move to pre-commit.ci. (sorry for pre-commit authors). And since github actions now work due to your excellent PR #131,  I'm happy to keep it the way it is for the time being.

**Pull request closed without merging**
