### PR TITLE
Add Documatt Theme

### PR DESCRIPTION
**Pull request by mattdocumatt**
Second attempt :-)

Hello, is it possible to add my "Documatt Theme"? It was originally for just my blog, but I open-sourced it recently.

* package name is `sphinx-documatt-theme`
* `html_theme` is `sphinx_documatt_theme`
* PyPI: https://pypi.org/project/sphinx-documatt-theme/
* real demo: https://blog.documatt.com/

All added to themes.json.

### CODE REVIEW

**Comment by mattdocumatt** [comment]
I'm so pleased! When it will be published to sphinx-themes.org?

**Comment by pradyunsg** [comment]
Once https://github.com/sphinx-themes/sphinx-themes.org/issues/25 is resolved, we'll update sphinx-themes.org to the current master (I'm calling it the v2 website -- see #19 for context).

You can see the current v2 website here: https://sphinx-themes.github.io/sphinx-themes.org/

**Comment by pradyunsg** [comment]
OH, and many thanks for filing this PR! ^>^

**Comment by mattdocumatt** [comment]
Ok, it is not problem. I'm only waiting to moment to say "Hey, mum, my
theme is on sphinx-themes.org" :-)

New website looks so good! Pradyun, you are magician. I thank to you for
your work on maintaining sphinx-themes.org!

**Comment by pradyunsg** [comment]
FYI: you inspired #32 -- here's a link to documatt on the v2 website: https://sphinx-themes.github.io/sphinx-themes.org/#theme-sphinx-documatt-theme :)

**Pull request merged**
