### PR TITLE
Fix redirecting links

### PR DESCRIPTION
**Pull request by stevepiercy**
See #149.

Partially fixes that issue, except for linked images, and the curl command, which could be added to `linkcheck_ignore`.

### CODE REVIEW

**Comment by pradyunsg** [comment]
> `linkcheck_ignore`

Could you go ahead and add those into this configuration variable?

**Comment by stevepiercy** [comment]
@pradyunsg I would if I knew where the `conf.py` exists. Is it in another repo?

Also I would only add `http://someurl/` to `linkcheck_ignore`.

I am not sure whether you would prefer to use locally hosted images instead of a third-party which can change its URLs without notice and potentially redirect to a link farm or other nefarious site.

Please let me know. Thank you!

**Comment by pradyunsg** [comment]
Here ya go: https://github.com/sphinx-themes/sphinx-themes.org/blob/master/src/templates/conf.template.py

> a third-party which can change its URLs without notice

It's not without notice -- the link is explicitly to a redirect intentionally, since you get a picture of a different cute animal each day. :)

> potentially redirect to a link farm or other nefarious site.

Well, Unsplash is a reputable site and, AFAICT, a stable business. This isn't a concern I'd have about this.

Please do add the unsplash links to the `linkcheck_ignore`.

**Comment by stevepiercy** [comment]
Added someurl and unsplash to linkcheck_ignore template in https://github.com/sphinx-themes/sphinx-themes.org/pull/150/commits/749ad9a22e2e689825b4526e51b48aee49003e43

**Pull request closed without merging**
